/*
 * This file is generated by jOOQ.
 */
package com.github.joostvdg.cmg.analytics;


import com.github.joostvdg.cmg.analytics.tables.FlywaySchemaHistory;
import com.github.joostvdg.cmg.analytics.tables.Generationrequests;
import com.github.joostvdg.cmg.analytics.tables.records.FlywaySchemaHistoryRecord;
import com.github.joostvdg.cmg.analytics.tables.records.GenerationrequestsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<GenerationrequestsRecord> GENERATIONREQUESTS_PKEY = Internal.createUniqueKey(Generationrequests.GENERATIONREQUESTS, DSL.name("generationrequests_pkey"), new TableField[] { Generationrequests.GENERATIONREQUESTS.ID }, true);
}
