/*
 * This file is generated by jOOQ.
 */
package com.github.joostvdg.cmg.analytics;


import com.github.joostvdg.cmg.analytics.tables.FlywaySchemaHistory;
import com.github.joostvdg.cmg.analytics.tables.Generationrequests;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.generationrequests</code>.
     */
    public static final Generationrequests GENERATIONREQUESTS = Generationrequests.GENERATIONREQUESTS;
}
