/*
 * This file is generated by jOOQ.
 */
package com.github.joostvdg.cmg.analytics.tables.records;


import com.github.joostvdg.cmg.analytics.tables.Generationrequests;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GenerationrequestsRecord extends UpdatableRecordImpl<GenerationrequestsRecord> implements Record10<Integer, String, Long, Long, String[], String, String, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.generationrequests.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.generationrequests.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.generationrequests.request_id</code>.
     */
    public void setRequestId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.generationrequests.request_id</code>.
     */
    public String getRequestId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.generationrequests.generation_count</code>.
     */
    public void setGenerationCount(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.generationrequests.generation_count</code>.
     */
    public Long getGenerationCount() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.generationrequests.duration</code>.
     */
    public void setDuration(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.generationrequests.duration</code>.
     */
    public Long getDuration() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.generationrequests.parameters</code>.
     */
    public void setParameters(String[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.generationrequests.parameters</code>.
     */
    public String[] getParameters() {
        return (String[]) get(4);
    }

    /**
     * Setter for <code>public.generationrequests.map_type</code>.
     */
    public void setMapType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.generationrequests.map_type</code>.
     */
    public String getMapType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.generationrequests.game_type</code>.
     */
    public void setGameType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.generationrequests.game_type</code>.
     */
    public String getGameType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.generationrequests.timestamp_request</code>.
     */
    public void setTimestampRequest(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.generationrequests.timestamp_request</code>.
     */
    public LocalDateTime getTimestampRequest() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.generationrequests.host</code>.
     */
    public void setHost(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.generationrequests.host</code>.
     */
    public String getHost() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.generationrequests.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.generationrequests.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, Long, Long, String[], String, String, LocalDateTime, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, Long, Long, String[], String, String, LocalDateTime, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Generationrequests.GENERATIONREQUESTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Generationrequests.GENERATIONREQUESTS.REQUEST_ID;
    }

    @Override
    public Field<Long> field3() {
        return Generationrequests.GENERATIONREQUESTS.GENERATION_COUNT;
    }

    @Override
    public Field<Long> field4() {
        return Generationrequests.GENERATIONREQUESTS.DURATION;
    }

    @Override
    public Field<String[]> field5() {
        return Generationrequests.GENERATIONREQUESTS.PARAMETERS;
    }

    @Override
    public Field<String> field6() {
        return Generationrequests.GENERATIONREQUESTS.MAP_TYPE;
    }

    @Override
    public Field<String> field7() {
        return Generationrequests.GENERATIONREQUESTS.GAME_TYPE;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Generationrequests.GENERATIONREQUESTS.TIMESTAMP_REQUEST;
    }

    @Override
    public Field<String> field9() {
        return Generationrequests.GENERATIONREQUESTS.HOST;
    }

    @Override
    public Field<String> field10() {
        return Generationrequests.GENERATIONREQUESTS.USER_AGENT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getRequestId();
    }

    @Override
    public Long component3() {
        return getGenerationCount();
    }

    @Override
    public Long component4() {
        return getDuration();
    }

    @Override
    public String[] component5() {
        return getParameters();
    }

    @Override
    public String component6() {
        return getMapType();
    }

    @Override
    public String component7() {
        return getGameType();
    }

    @Override
    public LocalDateTime component8() {
        return getTimestampRequest();
    }

    @Override
    public String component9() {
        return getHost();
    }

    @Override
    public String component10() {
        return getUserAgent();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getRequestId();
    }

    @Override
    public Long value3() {
        return getGenerationCount();
    }

    @Override
    public Long value4() {
        return getDuration();
    }

    @Override
    public String[] value5() {
        return getParameters();
    }

    @Override
    public String value6() {
        return getMapType();
    }

    @Override
    public String value7() {
        return getGameType();
    }

    @Override
    public LocalDateTime value8() {
        return getTimestampRequest();
    }

    @Override
    public String value9() {
        return getHost();
    }

    @Override
    public String value10() {
        return getUserAgent();
    }

    @Override
    public GenerationrequestsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GenerationrequestsRecord value2(String value) {
        setRequestId(value);
        return this;
    }

    @Override
    public GenerationrequestsRecord value3(Long value) {
        setGenerationCount(value);
        return this;
    }

    @Override
    public GenerationrequestsRecord value4(Long value) {
        setDuration(value);
        return this;
    }

    @Override
    public GenerationrequestsRecord value5(String[] value) {
        setParameters(value);
        return this;
    }

    @Override
    public GenerationrequestsRecord value6(String value) {
        setMapType(value);
        return this;
    }

    @Override
    public GenerationrequestsRecord value7(String value) {
        setGameType(value);
        return this;
    }

    @Override
    public GenerationrequestsRecord value8(LocalDateTime value) {
        setTimestampRequest(value);
        return this;
    }

    @Override
    public GenerationrequestsRecord value9(String value) {
        setHost(value);
        return this;
    }

    @Override
    public GenerationrequestsRecord value10(String value) {
        setUserAgent(value);
        return this;
    }

    @Override
    public GenerationrequestsRecord values(Integer value1, String value2, Long value3, Long value4, String[] value5, String value6, String value7, LocalDateTime value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GenerationrequestsRecord
     */
    public GenerationrequestsRecord() {
        super(Generationrequests.GENERATIONREQUESTS);
    }

    /**
     * Create a detached, initialised GenerationrequestsRecord
     */
    public GenerationrequestsRecord(Integer id, String requestId, Long generationCount, Long duration, String[] parameters, String mapType, String gameType, LocalDateTime timestampRequest, String host, String userAgent) {
        super(Generationrequests.GENERATIONREQUESTS);

        setId(id);
        setRequestId(requestId);
        setGenerationCount(generationCount);
        setDuration(duration);
        setParameters(parameters);
        setMapType(mapType);
        setGameType(gameType);
        setTimestampRequest(timestampRequest);
        setHost(host);
        setUserAgent(userAgent);
    }
}
